- hosts: k-vms
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
    - name: 'ensure user {{ project_name }} exists'
      user: name={{ project_name }} state=present
