- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: 
    user:
      name: testbunny
      state: absent
      # remove destroys files associated with account
      remove: yes
    become: true 
