---
- hosts: my_hosts
  remote_user: phoenix_person
#  vars_prompt:
#    - name: "some_password"
#      prompt: "Enter password"
#      private: yes
  tasks:
    - name: install zsh
      apt: 
        update_cache: yes
        cache_valid_time: 30
