---
- hosts: matrixbaremetals
  remote_user: dock-bot
  tasks:
  - name: ensure python-pip is installed
    apt:
      name: python-pip
      state: present
    become: yes
  - name: ensure python3 is installed
    apt:
      name: python3-pip
      state: present
    become: yes
#  - name: ensure python2-pip is removed
#    apt:
#      name: python2-pip
#      state: absent
#      become: true
#  - name: ensure python3-pip is removed
#    apt:
#      name: python3-pip
#      state: absent
#      become: true
