---
- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: ensure python is at the latest version
    apt:
      name: python
      state: latest
  - name: ensure python3 is at the latest version
    apt:
      name: python3
      state: latest
