---
- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: ensure puppet is installed
    apt:
      name: puppet
      #state: present
      #state: latest
      only-upgrade: yes
    become: yes
