---
- hosts: hyper-vms
  remote_user: dock-bot
  tasks:
  - name: ensure python2 is at the latest version
    yum:
      name: python
      state: latest
  - name: ensure python3 is at the latest version
    yum:
      name: python36u
      state: latest
