- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: "yum install docker prerequisite packages"
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - ca-certificates
      - curl
      - gnupg2
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
    become: yes
# # # lint for single docker repo # # #
#  - name: "wget docker-ce.repo to /etc/yum.repos.d/"
#    command: wget "https://download.docker.com/linux/centos/docker-ce.repo" /etc/yum.repos.d/
#    become: yes
  - name: "yum update"
      yum: 
        list: repos
        update_cache: yes
   
