- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: "yum install docker-ce from repo"
    yum:
      name: docker-ce
      state: present
    environment:
      RUNLEVEL: 1
    become: yes
