---
- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name: ensure docker-compose is installed
    pip:
      executable: pip3
      name: docker-compose
      state: present
    become: yes
