- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
  - name:  "\n >> /etc/hosts"
    lineinfile:
      backup: yes
      path: ~/.bashrc
      create: no
      insertafter: EOF
      line: "export PATH=$PATH:/opt/puppetlabs/bin"
      state: present
    become: false
