---
- hosts: my_hosts
  remote_user: phoenix_person
  tasks:
    - name: install zsh
      yum: 
        name: zsh
        state: present  
      when: (ansible_facts['distribution'] == "CentOS") or
            (ansible_facts['distribution'] == "RedHat") 
      become: true
    - name: install zsh
      apt: 
        name: zsh
        state: present  
      when: (ansible_facts['distribution'] == "Debian") or
            (ansible_facts['distribution'] == "Ubuntu")
      become: true
